"""empty message

Revision ID: f5547ff39514
Revises: c28c834dee85
Create Date: 2026-02-19 16:33:58.890559

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5547ff39514"
down_revision: str | Sequence[str] | None = "c28c834dee85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=True),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_app_users_email"), "app_users", ["email"], unique=True)
    op.create_index(op.f("ix_app_users_user_id"), "app_users", ["user_id"], unique=False)
    op.create_index(op.f("ix_app_users_username"), "app_users", ["username"], unique=True)
    op.create_table(
        "app_sessions",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("refresh_count", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_activity_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(op.f("ix_app_sessions_refresh_token_hash"), "app_sessions", ["refresh_token_hash"], unique=False)
    op.create_index(op.f("ix_app_sessions_session_id"), "app_sessions", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_sessions_session_id"), table_name="app_sessions")
    op.drop_index(op.f("ix_app_sessions_refresh_token_hash"), table_name="app_sessions")
    op.drop_table("app_sessions")
    op.drop_index(op.f("ix_app_users_username"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_user_id"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_email"), table_name="app_users")
    op.drop_table("app_users")
    # ### end Alembic commands ###
